services:
  # MinIO Object Storage Service
  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z
    container_name: file-sharing-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - file-sharing-network

  # Go Backend Service
  backend:
    build:
      context: ./Go
      dockerfile: Dockerfile
    container_name: file-sharing-backend
    ports:
      - "8000:8000"
    environment:
      - LOCAL_IP=minio:9000
      - ACCESS_KEY=minioadmin
      - SECRET_KEY=minioadmin123
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - file-sharing-network
    restart: unless-stopped

  # Flutter Frontend Service
  frontend:
    build:
      context: ./filesharing
      dockerfile: Dockerfile
      args:
        API_BASE_URL: http://backend:8000
    container_name: file-sharing-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - file-sharing-network
    restart: unless-stopped

volumes:
  minio_data:
    driver: local

networks:
  file-sharing-network:
    driver: bridge